# Site settings
title: mitos[dash]kalandiel - coding
email: webmaster@mitos-kalandiel.me
description: > # this means to ignore newlines until "baseurl:"
  Joker Solutions code is mostly C# and PHP 5.x applications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code.mitos-kalandiel.me" # the base hostname & protocol for your site
twitter_username: mitoskalandiel
github_username:  mitoskalandiel

# Build settings
markdown: kramdown
